# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31cbc656c454cb17af833f31c81cdac562bbd9505a9a884840f71a6bcdd60976c154dd167df8e6320b1ccc1527e985f1262917b39af989d5a5e36acb77b94f64

test:
  secret_key_base: c6870271827c725abae5976157def44ed3a38892601d8f386f1cfedde37484d7beaa7b9ec8fc19b9d1b18712d15287cb5c63485ff16506ae7ea0b8ee592a6679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
